onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /lab7_top_tb/KEY
add wave -noupdate /lab7_top_tb/SW
add wave -noupdate /lab7_top_tb/LEDR
add wave -noupdate /lab7_top_tb/HEX0
add wave -noupdate /lab7_top_tb/HEX1
add wave -noupdate /lab7_top_tb/HEX2
add wave -noupdate /lab7_top_tb/HEX3
add wave -noupdate /lab7_top_tb/HEX4
add wave -noupdate /lab7_top_tb/HEX5
add wave -noupdate /lab7_top_tb/err
add wave -noupdate /lab7_top_tb/DUT/KEY
add wave -noupdate /lab7_top_tb/DUT/SW
add wave -noupdate /lab7_top_tb/DUT/LEDR
add wave -noupdate /lab7_top_tb/DUT/HEX0
add wave -noupdate /lab7_top_tb/DUT/HEX1
add wave -noupdate /lab7_top_tb/DUT/HEX2
add wave -noupdate /lab7_top_tb/DUT/HEX3
add wave -noupdate /lab7_top_tb/DUT/HEX4
add wave -noupdate /lab7_top_tb/DUT/HEX5
add wave -noupdate /lab7_top_tb/DUT/dout_en
add wave -noupdate /lab7_top_tb/DUT/sw_en
add wave -noupdate /lab7_top_tb/DUT/ledr_load
add wave -noupdate /lab7_top_tb/DUT/read_data_cpu
add wave -noupdate /lab7_top_tb/DUT/mem_cmd
add wave -noupdate /lab7_top_tb/DUT/mem_addr
add wave -noupdate /lab7_top_tb/DUT/write_data
add wave -noupdate /lab7_top_tb/DUT/N
add wave -noupdate /lab7_top_tb/DUT/V
add wave -noupdate /lab7_top_tb/DUT/Z
add wave -noupdate /lab7_top_tb/DUT/read_address
add wave -noupdate /lab7_top_tb/DUT/write_address
add wave -noupdate /lab7_top_tb/DUT/din
add wave -noupdate /lab7_top_tb/DUT/write
add wave -noupdate /lab7_top_tb/DUT/dout
add wave -noupdate /lab7_top_tb/DUT/CPU/clk
add wave -noupdate /lab7_top_tb/DUT/CPU/reset
add wave -noupdate /lab7_top_tb/DUT/CPU/read_data
add wave -noupdate /lab7_top_tb/DUT/CPU/write_data
add wave -noupdate /lab7_top_tb/DUT/CPU/mem_cmd
add wave -noupdate /lab7_top_tb/DUT/CPU/mem_addr
add wave -noupdate /lab7_top_tb/DUT/CPU/N
add wave -noupdate /lab7_top_tb/DUT/CPU/V
add wave -noupdate /lab7_top_tb/DUT/CPU/Z
add wave -noupdate /lab7_top_tb/DUT/CPU/next_pc
add wave -noupdate /lab7_top_tb/DUT/CPU/PC
add wave -noupdate /lab7_top_tb/DUT/CPU/data_addr
add wave -noupdate /lab7_top_tb/DUT/CPU/in_load
add wave -noupdate /lab7_top_tb/DUT/CPU/nsel_id
add wave -noupdate /lab7_top_tb/DUT/CPU/instruction_id
add wave -noupdate /lab7_top_tb/DUT/CPU/sximm5_id
add wave -noupdate /lab7_top_tb/DUT/CPU/sximm8_id
add wave -noupdate /lab7_top_tb/DUT/CPU/ALUop_id
add wave -noupdate /lab7_top_tb/DUT/CPU/shift_id
add wave -noupdate /lab7_top_tb/DUT/CPU/op_id
add wave -noupdate /lab7_top_tb/DUT/CPU/writenum_id
add wave -noupdate /lab7_top_tb/DUT/CPU/opcode_id
add wave -noupdate /lab7_top_tb/DUT/CPU/readnum_id
add wave -noupdate /lab7_top_tb/DUT/CPU/mdata
add wave -noupdate /lab7_top_tb/DUT/CPU/sximm8_data
add wave -noupdate /lab7_top_tb/DUT/CPU/sximm5_data
add wave -noupdate /lab7_top_tb/DUT/CPU/PC_data
add wave -noupdate /lab7_top_tb/DUT/CPU/w_data
add wave -noupdate /lab7_top_tb/DUT/CPU/loada_data
add wave -noupdate /lab7_top_tb/DUT/CPU/loadb_data
add wave -noupdate /lab7_top_tb/DUT/CPU/loadc_data
add wave -noupdate /lab7_top_tb/DUT/CPU/loads_data
add wave -noupdate /lab7_top_tb/DUT/CPU/asel_data
add wave -noupdate /lab7_top_tb/DUT/CPU/bsel_data
add wave -noupdate /lab7_top_tb/DUT/CPU/vsel_data
add wave -noupdate /lab7_top_tb/DUT/CPU/readnum_data
add wave -noupdate /lab7_top_tb/DUT/CPU/writenum_data
add wave -noupdate /lab7_top_tb/DUT/CPU/shift_data
add wave -noupdate /lab7_top_tb/DUT/CPU/ALUop_data
add wave -noupdate /lab7_top_tb/DUT/CPU/opcode_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/op_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/loada_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/loadb_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/loadc_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/loads_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/asel_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/bsel_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/w_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/reset_pc
add wave -noupdate /lab7_top_tb/DUT/CPU/load_pc
add wave -noupdate /lab7_top_tb/DUT/CPU/load_ir
add wave -noupdate /lab7_top_tb/DUT/CPU/addr_sel
add wave -noupdate /lab7_top_tb/DUT/CPU/load_addr
add wave -noupdate /lab7_top_tb/DUT/CPU/vsel_fsm
add wave -noupdate /lab7_top_tb/DUT/CPU/nsel_fsm
add wave -noupdate /lab7_top_tb/DUT/MEM/clk
add wave -noupdate /lab7_top_tb/DUT/MEM/read_address
add wave -noupdate /lab7_top_tb/DUT/MEM/write_address
add wave -noupdate /lab7_top_tb/DUT/MEM/write
add wave -noupdate /lab7_top_tb/DUT/MEM/din
add wave -noupdate /lab7_top_tb/DUT/MEM/dout
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {965 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 284
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {695 ps} {1587 ps}
